name: Sync and Compile DirectGR Rules

on:
  schedule:
    - cron: '0 18 1 * *'  # 北京时间 02:00 执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  DirectGR_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch DirectGR Rules
      run: |
        mkdir -p rules/Domain  # 确保目录存在

        # 下载 DirectGR 规则文件
        curl -sL "https://raw.githubusercontent.com/Rcftngqmgq/ClashRules/refs/heads/main/rules/Domain/DirectGR.list" -o rules/Domain/DirectGR.list

    - name: Extract DOMAIN and DOMAIN-SUFFIX rules from DirectGR.list
      run: |
        # 提取 DOMAIN-SUFFIX 规则并加上 *.
        grep -Eo 'DOMAIN-SUFFIX,[^,]+' rules/Domain/DirectGR.list | sed 's/DOMAIN-SUFFIX,//' | sed 's/^/*./' > rules/Domain/DirectGR-domain.list
        # 提取 DOMAIN 规则
        grep -Eo 'DOMAIN,[^,]+' rules/Domain/DirectGR.list | sed 's/DOMAIN,//' >> rules/Domain/DirectGR-domain.list

    - name: Convert DirectGR Rules to YAML
      run: |
        echo "payload:" > rules/Domain/DirectGR.yaml
        sort -u rules/Domain/DirectGR-domain.list | awk '{print "  - \047" $0 "\047"}' >> rules/Domain/DirectGR.yaml

    - name: Convert DirectGR Rules to MRS
      run: |
        # 使用 mihomo 转换为 MRS 格式
        mihomo convert-ruleset domain yaml rules/Domain/DirectGR.yaml rules/Domain/DirectGR.mrs
        rm -f rules/Domain/DirectGR-domain.list

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated DirectGR rules (DirectGR.list -> DirectGR.mrs)" && git push)
